language: java
jdk:
  - openjdk8
branches:
  only:
    - homework
env:
  global:
    - S3_BUCKET_NAME=jimmy-learning-deploybucket-elvj6c5l7yv8
    - CODEDEPLOY_APPLICATION=jimmy-Application
    - CODEDEPLOY_GROUP=master
    - REGION=ap-northeast-1
    - LOCAL_DIR=deploy
    - secure: nKWhQMFN6AW7fDWVowQ1HB3Xl8KdV54D6ejXN74cI5E8eyD8RZZ2Ik3spMsn1n1PdqsV0pQcVHJ7cRLC3+3ImKVuwdi2u7ejbPWufqT3ctKLHjTnBVzFjF5ljfGEzJmEaeEbm9ehUOwBYmx79I7s8AZ78uy0od4cjZ9mFD3aP4CDkecahDeYisy/gud+drATLPshxhC9EB5OfW/8WIu4c1F5c//hhcmTntJFwNDerQiC0AT7f8Spmwf5+ddsE15nY6/OH0kjs733nM6wscSi3Lb4N/4mo3JcWDWlz+AGminrDUfPExoUqFkMZWipksv5mHr0g4aeyAVvd3kVICRHoCieTJPRvqm4xReQPrRLpnI0LFi4vIpFylH2SgCamPf/tqbhrKJStAfNGZpSCjo2W/N0XTrIdVpqDAiAp5HcD5NK+hGbnHlzD7IQXk0wissPsD1RyxC2s/9UA+IxIPtU6rWBLNMtXT9CeoA0nVrrxd0Msab8y7Pgr2FH+EBjPB1n6Odn+fxXdYHjeP7yOGX6V53luqdITAwdFpjevNEhcPhx3kiRddnT4tXh/R3c8tLu6CdKNzewVe+w9LZ3Omvmu19X2r+KDvZGYT8YS/MtS3z41bQJrolkh4JvWKwtjFFhoKd0U/LWZprZm0Wk1rhIgGTtbujQ2sVtUvMSV9B3FqY=
    - secure: I47T+LVveSJf6Cd7cv/lRM2fZgNiPQOY8GNyEKtBFT5nYWehvXJcCIydF+oRaVI3utzNp6KZS3ruiHhr7b2x/eDzCbFVpvYR+Wx9Kqi/fgFe3Miuk5XUlpgLLNKQaV+J6LCzXr3NboDxwe9kfKwwlhEujHlhyWOiTADmvb67WLG4ugskENHurfhq3cgEE/qnMos+RRtJXLj5nghQa07xEavxqWe73XBtz/TBuZqWX68hi3NZjT8Sp/LV/Jjku7JThxVtZQKl/6AHOBvVpv1TRfe5dyUn2ldYlcQzMe+klA3phu65WeJgI7UvdIvnoW0kgF5B2I19bQdbogGnqf8QT8QqYjFtCudecBtbZqCgx3HnoM4kMMQ5AQYIG1uFv6iDZpkRn/xltQZVztXhCMiGuzQ6rJjb8bkI31qIdyioLdVzdROlTBpH99YKGwtclOErbTdwRlSRtBWPyq8o3+jibam9hGcDrblty9qTgqpaX+eJj7jkbCrVBNNX8+kDpgemu0LjXnDIjpnfMAIlK3rEIgEAwwswelitmu1CqfPP5yh5sPNaISn9oNXP8himHA1ItpIgA6/vpK1EbkBdq3SVEbG4qY3Z+fKEJBkSEH5RNMGDG++Fu5pUndDZUKSJ8t1gsx/LPVdygqfCEL+WOu54zUYr5jSnWirgjB2Vsb0bQSU=
script:
  - gradle build
  - mkdir ${LOCAL_DIR}
  - mv build/libs/example.war ROOT.war
  - zip release ROOT.war scripts/* appspec.yml
  - mv release.zip ${LOCAL_DIR}/
deploy:
  - provider: s3
    bucket: '$S3_BUCKET_NAME'
    access_key_id: '$AWS_ACCESS_KEY_ID'
    secret_access_key: '$AWS_SECRET_ACCESS_KEY'
    local_dir: '$LOCAL_DIR'
    skip_cleanup: true
    region: '$REGION'
    on:
      branch: homework
  - provider: codedeploy
    bucket: '$S3_BUCKET_NAME'
    access_key_id: '$AWS_ACCESS_KEY_ID'
    secret_access_key: '$AWS_SECRET_ACCESS_KEY'
    key: release.zip
    application: '$CODEDEPLOY_APPLICATION'
    deployment_group: '$CODEDEPLOY_GROUP'
    region: '$REGION'
    on:
      branch: homework
