language: java
jdk:
  - openjdk8
branches:
  only: homework
env:
  global:
    - S3_BUCKET_NAME=jimmy-aws-training-homework-deploybucket-mr08q23q3j2u
    - CODEDEPLOY_APPLICATION=jimmy-Application
    - CODEDEPLOY_GROUP=master
    - REGION=ap-northeast-1
    - LOCAL_DIR=deploy
    - secure: pe82giYVCaviJ2IfsfoaO3pqpQId4mcPnlM/yQmJAE/LWVxZK+jYiCUW9exG4CdsiQTt3z0qNmsmDHAJGAL8EpbTJZ8QT0kKUimUKuIryzkOKHFiLvHCI3UR8GXQxvn3KOOkw2sQQQhf49+pdKEhRVlqtX6m1imX8+oQm6ONV/QU8ClG8aPeQxlDp0+QnQYPxUey5eaNzJkHWqDcoOoWfn2Z+NBnDRFc7CI6iVGZDpc+/GD5Ums6akeBDn0wdnhCCGY60M2W/oh3P8p5RzP6G6oKJsNpby/Y/U1VHQEiv8rxIAycflrUs6MmNlIbf0FYS7v8FQ0vb5vQ4QVW/tqagRHFwRk/krhIafGMNmchfQLFpN6sWVv/g/hzM9hc6xwfRl1vtpJv7ErZP4o0N6/zprJcHlJ+CluZkV3mLeGJjlnuSX6WrKDDqmolNH1j452vPxR/R3VW9YljF/wU0neVyOsOHDyMdXBmSB5pG4VSIWSo7+JN72SAtP39+qpQ6Pkko4c0KHgod6cCZ4Vu2tDE7vCiiLomXNJyvRb+0PVCz57eY+D/ufF4nM6auy8+43qB2hMtGparu7oMCQxo6bNkxS/34TI8zRsLi2+VF9ZIgI/6h+x63miX/gSvgrtUEuFK6HNu2P6s2ezBTetwAziL4rgUTCUMgTjqaaAy+idHzlM=
    - secure: eeB3LTGGsjYUwqID3zERxQX2aSiA8iTwmFkFg8EbWXBO9Kwz++NR6QAooORdAuJYBx6J23jZS8TA56QyjBtF+SkxGBbrfN6+OPSbbQh67hyh8C8tpawHRpI5kWd8HSPDuADn/b4FSLxbIZ+uaNm3fCDiKsAwd1hyprwS2huPRDV/rgQwoo+vGh0mbcydjzu3dOaENo1O270UbBcoQhbQlzd5Azm9Rig9VdCI9s3glZIetPv+01yxZ8pgPxrFOGKzCUoeS7BHkNwfBBqQCffKAeC+DL7/TSoqy+kmWLlkPB3S1LjFC+KtN4QpiM+VO535acit2eI8fTdJMgoAmfSSP2+IoYcWHgw+LN98T0LsjJnAFz6Q+EVnkqHDl54py9hmTdlfaF4sqU8JaomUgcHiCIQMvg0+olW3uLxIDxQmBbwz0tiCtHxKQlmyaasozuK6mYBLT/DkgxSrrqemaoZ6pr/pO7SLlG/lWtlMK/xpwobG93RMAjQbJ1Tp/yDcsEfCvTFFQtqXiwlnzwyLEIVfon9LZpcfnK6WH34DKvKBubgE2qlxEyvz9nLVlXHeZ1SFm4TyIfJSwxRqGPdJeWdOWxQQwW4+B//W3Eu6cG8NQFW8UQPAnaYBZVb7ZDptu89tLsLwLXoeFsCpAzEmUFYYsp7VqeRI386jHotNkHljPyI=
script:
  - gradle build
  - mkdir ${LOCAL_DIR}
  - mv build/libs/example.war ROOT.war
  - zip release ROOT.war scripts/* appspec.yml
  - mv release.zip ${LOCAL_DIR}/
deploy:
  - provider: s3
    bucket: '$S3_BUCKET_NAME'
    access_key_id: '$AWS_ACCESS_KEY_ID'
    secret_access_key: '$AWS_SECRET_ACCESS_KEY'
    local_dir: '$LOCAL_DIR'
    skip_cleanup: true
    region: '$REGION'
    on:
      branch: homework
  - provider: codedeploy
    bucket: '$S3_BUCKET_NAME'
    access_key_id: '$AWS_ACCESS_KEY_ID'
    secret_access_key: '$AWS_SECRET_ACCESS_KEY'
    key: release.zip
    application: '$CODEDEPLOY_APPLICATION'
    deployment_group: '$CODEDEPLOY_GROUP'
    region: '$REGION'
    on:
      branch: homework
